//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema86Movie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN86_Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CN86_Pelicula()
        {
            this.CN86_Capitulos_Anterior = new HashSet<CN86_Capitulos_Anterior>();
        }
    
        public int Id_Pelicula { get; set; }
        public int Id_Tipo { get; set; }
        public string Titulo { get; set; }
        public string Resenia { get; set; }
        public string Detalles { get; set; }
        public string URL_Ubicacion { get; set; }
        public string TorrentName { get; set; }
        public string PathImg { get; set; }
        public string Ubicacion { get; set; }
        public int Id_Genero { get; set; }
        public string URL_Trailer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN86_Capitulos_Anterior> CN86_Capitulos_Anterior { get; set; }
        public virtual CN86_Genero CN86_Genero { get; set; }
        public virtual CN86_Tipo CN86_Tipo { get; set; }
    }
}
