//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema86Movie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN86_Capitulos_Anterior
    {
        public int Id_Capitulo { get; set; }
        public string Titulo { get; set; }
        public string URL_Ubicacion { get; set; }
        public string TorrentName { get; set; }
        public Nullable<int> Id_Pelicula { get; set; }
    
        public virtual CN86_Pelicula CN86_Pelicula { get; set; }
    }
}
