//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema86Movie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN86_Genero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CN86_Genero()
        {
            this.CN86_Pelicula = new HashSet<CN86_Pelicula>();
        }
    
        public int Id_Genero { get; set; }
        public string DescripcionGenero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN86_Pelicula> CN86_Pelicula { get; set; }
    }
}
