//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema86Movie.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A4B7B0_Cinema86Entities : DbContext
    {
        public DB_A4B7B0_Cinema86Entities()
            : base("name=DB_A4B7B0_Cinema86Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CN86_Capitulos_Anterior> CN86_Capitulos_Anterior { get; set; }
        public virtual DbSet<CN86_Estado> CN86_Estado { get; set; }
        public virtual DbSet<CN86_Estatus_Usuario> CN86_Estatus_Usuario { get; set; }
        public virtual DbSet<CN86_Genero> CN86_Genero { get; set; }
        public virtual DbSet<CN86_Pelicula> CN86_Pelicula { get; set; }
        public virtual DbSet<CN86_Tipo> CN86_Tipo { get; set; }
        public virtual DbSet<CN86_Usuario> CN86_Usuario { get; set; }
    }
}
